name: Build OpenWrt Docker x86-64 image

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"

env:
  FIRMWARE_URL: "https://static.cowtransfer.com/cloud-ad359ef4-aec9-4427-9fb7-1ea7cc4dfed9%2Fa93d2010-8760-4687-8ac2-54bf3cdf6e76%2Fopenwrt-bcm27xx-bcm2711-rpi-4-rootfs.tar.gz?t-s=1594469260277&t-c=1594469033996&attname=openwrt-bcm27xx-bcm2711-rpi-4-rootfs.tar.gz&attname=%E5%A5%B6%E7%89%9B%E5%BF%AB%E4%BC%A0.zip"
  REPOSITORY: ilovesuyy/openwrt
  TAG: pi4

jobs:
  build:
    name: "Build OpenWrt docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Firmware
        run: |
          wget $FIRMWARE_URL -O openwrt.tar.gz

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          FIRMWARE: openwrt.tar.gz
        with:
          name: ${{ env.REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: FIRMWARE
          tags: "latest,${{ env.TAG }}"
